# Generated by Django 5.2.8 on 2025-11-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course_start', models.CharField(max_length=100)),
                ('course_end', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
            ],
        ),
    ]
