# Generated by Django 5.2.8 on 2025-11-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_start',
            field=models.DateField(),
        ),
    ]
